services:
  tts_bot:
    build: .
    container_name: tts_bot_container
    volumes:
      - tts_bot_audio:/app/tts_bot_audio
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ENV=prod
    networks:
      - app-network

  local-test-db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: user-system-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d user_system"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  tts_bot_audio:
  postgres_data: