services:
  tts_bot:
    build: .
    container_name: tts_bot_container
    volumes:
      - tts_bot_audio:/app/tts_bot_audio
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ENV=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  tts_bot_audio: